### ISSUE TITLE
Clicking on blank line

### ISSUE THREAD

**Issue by davidpmerle** [gneils/guiprocf-git#3]
If you click from a keyed record type to a blank line, the key windows stays open with the previous keys. If you then double click the key value, it brings up the previously selected record type.

**Comment by gneils** [comment]
Removed blank lines from default display.  If someone customizes with blank lines I will have to figure that out.

**Comment by gneils** [comment]
Blank lines no longer display the last visible keys.  In addition they disable buttons like "New Record", "Table" and "View Record".  

It checks the value of Record Type.  If that is set to missing, these settings are triggered.
