### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by davidpmerle** [gneils/guiprocf-git#4]
The No Data indicator text in the key windows can be repeated any number of times depending on how many times the record type is clicked.

Also, the message box that appears when "No Data" is clicked is "There is no data", it might be more informative to have a message like "There is no record for this ID. Click "New Form" if you want to create a new record."

**Comment by gneils** [comment]
The key display was being run through multiple times. The subprocedure was incorrectly called before the data was retrieved.  Now the data is retrieved, processed and then displayed.
