### ISSUE TITLE
Spacing on Record Types

### ISSUE THREAD

**Issue by davidpmerle** [gneils/guiprocf-git#6]
Maybe its just because I'm not used to it, but I can't love the spacing after every 5 record types. It seems arbitrary and I keep thinking the blank line must be something important. Perhaps a line ------------------------------- instead? Though, I must say, I have never been bothered by the continuity of record types. In MIND, I broke them up into groups, but only because there were logic groups of record types and I used a line as separator. A space after every 5 seems arbitrary and inexplicable.

**Comment by gneils** [comment]
I removed the code to add blank lines.  The default will not to have blank lines.  People can override this if they want to in a GUI_CUSTOM.REC_LIST_LOAD.
